services:
  task-manager:
    build: ./backend
    container_name: server
    ports:
      - "5678:5678"
    env_file:
      - ./backend/.env
    volumes:
      - ../certs:/app/certs
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"

volumes:
  database_data:
    driver: local
