DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS boards CASCADE;

DROP TABLE IF EXISTS board_users CASCADE;

DROP TABLE IF EXISTS tasks CASCADE;

DROP TABLE IF EXISTS lists CASCADE;

DROP TABLE IF EXISTS board_invitations CASCADE;

DROP TABLE IF EXISTS task_assignees CASCADE;

DROP TABLE IF EXISTS comments CASCADE;
